### ISSUE TITLE
Navbar doesn't have a background in Firefox (Desktop & Mobile)

### ISSUE THREAD

**Issue by VentGrey** [UpVent/upvent-svelte#36]
This is the faulty code:

```css
    @supports (backdrop-filter: none) {
	    .navbar-upvent {
            backdrop-filter: saturate(100%) blur(100px);
            -webkit-backdrop-filter: saturate(100%) blur(100px);
	    }
    }
    @supports not (backdrop-filter: none) {
        .background {
            background-color: #FAFAFA;
        }
    }
```
